//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeventhDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobless
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jobless()
        {
            this.Archives = new HashSet<Archives>();
        }
    
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public byte Age { get; set; }
        public string Passport { get; set; }
        public System.DateTime PassportDate { get; set; }
        public string Region { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public byte[] Picture { get; set; }
        public string StudyPlace { get; set; }
        public string StudyAddress { get; set; }
        public int StudyTypeID { get; set; }
        public int RegistratorID { get; set; }
        public System.DateTime RegDate { get; set; }
        public decimal Payment { get; set; }
        public bool Experience { get; set; }
        public string Comment { get; set; }
        public bool Used { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archives> Archives { get; set; }
        public virtual StudyTypies StudyTypies { get; set; }
        public virtual Users Users { get; set; }
    }
}
